Repository aws-powertools/powertools-lambda-layer-cdk, pull requests merged in 2024-03, with the labels that each got.

#82 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, auto-merge, size/XXL

#86 chore: remove unsupported runtimes
  src/lambda-powertools-layer.ts
  test/lambda-powertools-python-layer.test.ts
  test/lambda-powertools-typescript-layer.test.ts
Labels: size/XS

#87 chore: upgrade to jsii and TypeScript to 5.3.x
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  package-lock.json
  package.json
  yarn.lock
Labels: size/XXL

#90 chore(ci): bump jsii container image to node 20
  .github/workflows/upgrade-main.yml
Labels: size/XS
