Repository aws-powertools/powertools-lambda-layer-cdk, pull requests merged in 2024-08, with the labels that each got.

#101 chore: add powertools custom runner to run our release pipeline
  .github/workflows/release.yml
  .mergify.yml
Labels: size/S

#102 chore: remove package-lock and update deps
  .eslintrc.json
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package-lock.json
  package.json
  yarn.lock
Labels: size/XXL

#97 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, auto-merge, size/XXL
